openapi: 3.0.1
info:
  title: My Service
  description: This is my cool service.
  x-cortex-tag: {{cookiecutter.project_name}}
  x-cortex-type: service
  x-cortex-git:
    github:
      repository: kienan/cookiecutter-cortex-plugin
